export const PRELOAD_IMAGE_START = "PRELOAD_IMAGE_START";
export const PRELOAD_IMAGE_SUCCESS = "PRELOAD_IMAGE_SUCCESS";
export const PRELOAD_IMAGE_FAILURE = "PRELOAD_IMAGE_FAILURE";

export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

export const EDIT_PRODUCT_START = "EDIT_PRODUCT_START";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILURE = "EDIT_PRODUCT_FAILURE";

export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const ADD_SELECTED = "ADD_SELECTED";
export const SELECT_ALL = "SELECT_ALL";
export const SELECT_ARCHIVE_ALL = "SELECT_ARCHIVE_ALL";
export const CLEAR_SELECTED = "CLEAR_SELECTED";
export const CLEAR_SELECTED_ALL = "CLEAR_SELECTED_ALL";

export const DELETE_PRODUCTS_START = "DELETE_PRODUCTS_START";
export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS";
export const DELETE_PRODUCTS_FAILURE = "DELETE_PRODUCTS_FAILURE";

export const SET_EDIT = "SET_EDIT";

export const FETCH_EDIT_PRODUCT_START = "FETCH_EDIT_PRODUCT_START";
export const FETCH_EDIT_PRODUCT_SUCCESS = "FETCH_EDIT_PRODUCT_SUCCESS";
export const FETCH_EDIT_PRODUCT_FAILURE = "FETCH_EDIT_PRODUCT_FAILURE";

export const MOVE_TO_ARCHIVE_START = "MOVE_TO_ARCHIVE_START";
export const MOVE_TO_ARCHIVE_SUCCESS = "MOVE_TO_ARCHIVE_SUCCESS";
export const MOVE_TO_ARCHIVE_FAILURE = "MOVE_TO_ARCHIVE_FAILURE";

export const RESTORE_FROM_ARCHIVE_START = "RESTORE_FROM_ARCHIVE_START";
export const RESTORE_FROM_ARCHIVE_SUCCESS = "RESTORE_FROM_ARCHIVE_SUCCESS";
export const RESTORE_FROM_ARCHIVE_FAILURE = "RESTORE_FROM_ARCHIVE_FAILURE";

export const FETCH_ARCHIVE_PRODUCTS_START = "FETCH_ARCHIVE_PRODUCTS_START";
export const FETCH_ARCHIVE_PRODUCTS_SUCCESS = "FETCH_ARCHIVE_PRODUCTS_SUCCESS";
export const FETCH_ARCHIVE_PRODUCTS_FAILURE = "FETCH_ARCHIVE_PRODUCTS_FAILURE";

export const TOGGLE_STATUS_START = "TOGGLE_STATUS_START";
export const TOGGLE_STATUS_SUCCESS = "TOGGLE_STATUS_SUCCESS";
export const TOGGLE_STATUS_FAILURE = "TOGGLE_STATUS_FAILURE";

export const CHECK_ARTICLE_START = "CHECK_ARTICLE_START";
export const CHECK_ARTICLE_SUCCESS = "CHECK_ARTICLE_SUCCESS";
export const CHECK_ARTICLE_FAILURE = "CHECK_ARTICLE_FAILURE";

// CAT
export const SET_MODAL_EDIT = "SET_MODAL_EDIT";
export const SET_MODAL_NEW = "SET_MODAL_NEW";
export const SET_MODAL_DELETE = "SET_MODAL_DELETE";

export const ADD_CAT_START = "ADD_CAT_START";
export const ADD_CAT_SUCCESS = "ADD_CAT_SUCCESS";
export const ADD_CAT_FAILURE = "ADD_CAT_FAILURE";

export const RENAME_CAT_START = "RENAME_CAT_START";
export const RENAME_CAT_SUCCESS = "RENAME_CAT_SUCCESS";
export const RENAME_CAT_FAILURE = "RENAME_CAT_FAILURE";

export const FETCH_CAT_START = "FETCH_CAT_START";
export const FETCH_CAT_SUCCESS = "FETCH_CAT_SUCCESS";
export const FETCH_CAT_FAILURE = "FETCH_CAT_FAILURE";

export const SELECT_CAT = "SELECT_CAT";

export const CLEAR_SELECT_CAT = "CLEAR_SELECT_CAT";

export const REMOVE_CAT_START = "REMOVE_CAT_START";
export const REMOVE_CAT_SUCCESS = "REMOVE_CAT_SUCCESS";
export const REMOVE_CAT_FAILURE = "REMOVE_CAT_FAILURE";

export const MOVE_UP_CAT_START = "MOVE_UP_CAT_START";
export const MOVE_UP_CAT_SUCCESS = "MOVE_UP_CAT_SUCCESS";
export const MOVE_UP_CAT_FAILURE = "MOVE_UP_CAT_FAILURE";

export const MOVE_DOWN_CAT_START = "MOVE_DOWN_CAT_START";
export const MOVE_DOWN_CAT_SUCCESS = "MOVE_DOWN_CAT_SUCCESS";
export const MOVE_DOWN_CAT_FAILURE = "MOVE_DOWN_CAT_FAILURE";

export const TOGGLE_ADDING_SUCCESS = "TOGGLE_ADDING_SUCCESS";
export const TOGGLE_EDITING_SUCCESS = "TOGGLE_EDITING_SUCCESS";

// Дашборд
export const FETCH_STATISTIC_START = "FETCH_STATISTIC_START";
export const FETCH_STATISTIC_SUCCESS = "FETCH_STATISTIC_SUCCESS";
export const FETCH_STATISTIC_FAILURE = "FETCH_STATISTIC_FAILURE";

// Заказы
export const ADD_ORDER_PRODUCT_START = "ADD_ORDER_PRODUCT_START";
export const ADD_ORDER_PRODUCT_SUCCESS = "ADD_ORDER_PRODUCT_SUCCESS";
export const ADD_ORDER_PRODUCT_FAILURE = "ADD_ORDER_PRODUCT_FAILURE";

export const ADD_ORDER_START = "ADD_ORDER_START";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAILURE = "ADD_ORDER_FAILURE";

export const REMOVE_ORDER_START = "	REMOVE_ORDER_START";
export const REMOVE_ORDER_SUCCESS = "	REMOVE_ORDER_SUCCESS";
export const REMOVE_ORDER_FAILURE = "	REMOVE_ORDER_FAILURE";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILURE = "FETCH_ORDERS_FAILURE";

export const FETCH_LAST_ORDERS_START = "FETCH_LAST_ORDERS_START";
export const FETCH_LAST_ORDERS_SUCCESS = "FETCH_LAST_ORDERS_SUCCESS";
export const FETCH_LAST_ORDERS_FAILURE = "FETCH_LAST_ORDERS_FAILURE";

export const FETCH_ORDER_START = "FETCH_ORDER_START";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAILURE = "FETCH_ORDER_FAILURE";

export const CHANGE_STATUS_START = "CHANGE_STATUS_START";
export const CHANGE_STATUS_SUCCESS = "CHANGE_STATUS_SUCCESS";
export const CHANGE_STATUS_FAILURE = "CHANGE_STATUS_FAILURE";

export const SET_NOTE = "SET_NOTE";

export const FETCH_EDIT_ORDER_START = "FETCH_EDIT_ORDER_START";
export const FETCH_EDIT_ORDER_SUCCESS = "FETCH_EDIT_ORDER_SUCCESS";
export const FETCH_EDIT_ORDER_FAILURE = "FETCH_EDIT_ORDER_FAILURE";

export const EDIT_ORDER_START = "EDIT_ORDER_START";
export const EDIT_ORDER_SUCCESS = "EDIT_ORDER_SUCCESS";
export const EDIT_ORDER_FAILURE = "EDIT_ORDER_FAILURE";

export const SET_IMG = "SET_IMG";

export const FETCH_ORDER_NOTES_START = "FETCH_ORDER_NOTES_START";
export const FETCH_ORDER_NOTES_SUCCESS = "FETCH_ORDER_NOTES_SUCCESS";
export const FETCH_ORDER_NOTES_FAILURE = "FETCH_ORDER_NOTES_FAILURE";

export const SET_LAST_PARAMS = "SET_LAST_PARAMS";

export const SET_MODAL_ADD_PRODUCT = "SET_MODAL_ADD_PRODUCT";

export const SET_MODAL_ADD_MANAGER_NOTE = "SET_MODAL_ADD_MANAGER_NOTE";

export const GET_DELIVERY_PRICE_START = "GET_DELIVERY_PRICE_START";
export const GET_DELIVERY_PRICE_SUCCESS = "GET_DELIVERY_PRICE_SUCCESS";
export const GET_DELIVERY_PRICE_FAILURE = "GET_DELIVERY_PRICE_FAILURE";

export const ADD_MANAGER_NOTE_START = "ADD_MANAGER_NOTE_START";
export const ADD_MANAGER_NOTE_SUCCESS = "ADD_MANAGER_NOTE_SUCCESS";
export const ADD_MANAGER_NOTE_FAILURE = "ADD_MANAGER_NOTE_FAILURE";

export const REMOVE_NOTE_FROM_ORDER_START = "REMOVE_NOTE_FROM_ORDER_START";
export const REMOVE_NOTE_FROM_ORDER_SUCCESS = "REMOVE_NOTE_FROM_ORDER_SUCCESS";
export const REMOVE_NOTE_FROM_ORDER_FAILURE = "REMOVE_NOTE_FROM_ORDER_FAILURE";

export const ADD_ORDER_MANAGER_NOTE = "ADD_ORDER_MANAGER_NOTE";

export const SET_MODAL_PRICE_FILTER = "SET_MODAL_PRICE_FILTER";

export const SET_MODAL_ORDER_DELETE = "SET_MODAL_ORDER_DELETE";

export const SET_MODAL_ORDER_PREVIEW = "SET_MODAL_ORDER_PREVIEW";

export const SET_MODAL_ORDER_MANAGER_NOTES = "SET_MODAL_ORDER_MANAGER_NOTES";

export const SET_MODAL_ORDER_ERROR = "SET_MODAL_ORDER_ERROR";

// auth

export const PRELOAD_AVATAR_START = "PRELOAD_AVATAR_START";
export const PRELOAD_AVATAR_SUCCESS = "PRELOAD_AVATAR_SUCCESS";
export const PRELOAD_AVATAR_FAILURE = "PRELOAD_AVATAR_FAILURE";

export const REG_NEW_ADMIN_START = "REG_NEW_ADMIN_START";
export const REG_NEW_ADMIN_SUCCESS = "REG_NEW_ADMIN_SUCCESS";
export const REG_NEW_ADMIN_FAILURE = "REG_NEW_ADMIN_FAILURE";

export const SIGN_IN_START = "SIGN_IN_START";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";

export const TOGGLE_REG = "TOGGLE_REG";

export const TOGGLE_LOG = "TOGGLE_LOG";

export const RESTORE_START = "RESTORE_START";
export const RESTORE_SUCCESS = "RESTORE_SUCCESS";
export const RESTORE_FAILURE = "RESTORE_FAILURE";

export const SIGN_OUT = "SIGN_OUT";

// app

export const INIT_APP = "INIT_APP";

export const ADD_TOAST_MESSAGE = "ADD_TOAST_MESSAGE";

export const REMOVE_TOAST_MESSAGE = "REMOVE_TOAST_MESSAGE";

export const SET_TOOLTIP = "SET_TOOLTIP";

export const SET_TABLE_SIZE = "SET_TABLE_SIZE";

// users

export const FETCH_ADMINS_START = "FETCH_ADMINS_START";
export const FETCH_ADMINS_SUCCESS = "FETCH_ADMINS_SUCCESS";
export const FETCH_ADMINS_FAILURE = "FETCH_ADMINS_FAILURE";

export const TOGGLE_ACCESS_START = "TOGGLE_ACCESS_START";
export const TOGGLE_ACCESS_SUCCESS = "TOGGLE_ACCESS_SUCCESS";
export const TOGGLE_ACCESS_FAILURE = "TOGGLE_ACCESS_FAILURE";

// comments

export const FETCH_COMMENTS_START = "FETCH_COMMENTS_START";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE";

export const ADD_COMMENT_START = "ADD_COMMENT_START";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE";

export const APPLY_COMMENT_START = "APPLY_COMMENT_START";
export const APPLY_COMMENT_SUCCESS = "APPLY_COMMENT_SUCCESS";
export const APPLY_COMMENT_FAILURE = "APPLY_COMMENT_FAILURE";

export const REMOVE_COMMENT_START = "REMOVE_COMMENT_START";
export const REMOVE_COMMENT_SUCCESS = "REMOVE_COMMENT_SUCCESS";
export const REMOVE_COMMENT_FAILURE = "REMOVE_COMMENT_FAILURE";

export const SET_COMMENT_ANSWER = "SET_COMMENT_ANSWER";

export const ADD_ANS_START = "ADD_ANS_START";
export const ADD_ANS_SUCCESS = "ADD_ANS_SUCCESS";
export const ADD_ANS_FAILURE = "ADD_ANS_FAILURE";

export const REMOVE_COMMENT_ANS_START = "REMOVE_COMMENT_ANS_START";
export const REMOVE_COMMENT_ANS_SUCCESS = "REMOVE_COMMENT_ANS_SUCCESS";
export const REMOVE_COMMENT_ANS_FAILURE = "REMOVE_COMMENT_ANS_FAILURE";
