export const PRELOAD_IMAGE_START = "PRELOAD_IMAGE_START";
export const PRELOAD_IMAGE_SUCCESS = "PRELOAD_IMAGE_SUCCESS";
export const PRELOAD_IMAGE_FAILURE = "PRELOAD_IMAGE_FAILURE";

export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

export const EDIT_PRODUCT_START = "EDIT_PRODUCT_START";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILURE = "EDIT_PRODUCT_FAILURE";

export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const ADD_SELECTED = "ADD_SELECTED";
export const CLEAR_SELECTED = "CLEAR_SELECTED";
export const CLEAR_SELECTED_ALL = "CLEAR_SELECTED_ALL";

export const DELETE_PRODUCTS_START = "DELETE_PRODUCTS_START";
export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS";
export const DELETE_PRODUCTS_FAILURE = "DELETE_PRODUCTS_FAILURE";

export const SET_EDIT = "SET_EDIT";

export const FETCH_EDIT_PRODUCT_START = "FETCH_EDIT_PRODUCT_START";
export const FETCH_EDIT_PRODUCT_SUCCESS = "FETCH_EDIT_PRODUCT_SUCCESS";
export const FETCH_EDIT_PRODUCT_FAILURE = "FETCH_EDIT_PRODUCT_FAILURE";

// CAT
export const ADD_CAT_START = "ADD_CAT_START";
export const ADD_CAT_SUCCESS = "ADD_CAT_SUCCESS";
export const ADD_CAT_FAILURE = "ADD_CAT_FAILURE";

export const FETCH_CAT_START = "FETCH_CAT_START";
export const FETCH_CAT_SUCCESS = "FETCH_CAT_SUCCESS";
export const FETCH_CAT_FAILURE = "FETCH_CAT_FAILURE";

export const SELECT_CAT = "SELECT_CAT";

export const CLEAR_SELECT_CAT = "CLEAR_SELECT_CAT";

export const REMOVE_CAT_START = "REMOVE_CAT_START";
export const REMOVE_CAT_SUCCESS = "REMOVE_CAT_SUCCESS";
export const REMOVE_CAT_FAILURE = "REMOVE_CAT_FAILURE";

export const MOVE_UP_CAT_START = "MOVE_UP_CAT_START";
export const MOVE_UP_CAT_SUCCESS = "MOVE_UP_CAT_SUCCESS";
export const MOVE_UP_CAT_FAILURE = "MOVE_UP_CAT_FAILURE";

export const MOVE_DOWN_CAT_START = "MOVE_DOWN_CAT_START";
export const MOVE_DOWN_CAT_SUCCESS = "MOVE_DOWN_CAT_SUCCESS";
export const MOVE_DOWN_CAT_FAILURE = "MOVE_DOWN_CAT_FAILURE";

export const TOGGLE_ADDING_SUCCESS = "TOGGLE_ADDING_SUCCESS";

// Дашборд
export const FETCH_STATISTIC_START = "FETCH_STATISTIC_START";
export const FETCH_STATISTIC_SUCCESS = "FETCH_STATISTIC_SUCCESS";
export const FETCH_STATISTIC_FAILURE = "FETCH_STATISTIC_FAILURE";

// Заказы
export const ADD_ORDER_PRODUCT_START = "ADD_ORDER_PRODUCT_START";
export const ADD_ORDER_PRODUCT_SUCCESS = "ADD_ORDER_PRODUCT_SUCCESS";
export const ADD_ORDER_PRODUCT_FAILURE = "ADD_ORDER_PRODUCT_FAILURE";

export const ADD_ORDER_START = "ADD_ORDER_START";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAILURE = "ADD_ORDER_FAILURE";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILURE = "FETCH_ORDERS_FAILURE";

export const CHANGE_STATUS_START = "CHANGE_STATUS_START";
export const CHANGE_STATUS_SUCCESS = "CHANGE_STATUS_SUCCESS";
export const CHANGE_STATUS_FAILURE = "CHANGE_STATUS_FAILURE";
